---
- name: Install Krew plugins
  shell: "kubectl krew install {{ item }}"
  loop: '{{ krew_plugins | flatten(levels=1) }}'

- name: Upgrade Krew plugins
  shell: 'kubectl krew upgrade'
  when: krew_plugins_upgrade

